[2025-05-22T20:48:24.366+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_stream_dag.fetch_weather scheduled__2025-05-22T19:00:00+00:00 [queued]>
[2025-05-22T20:48:24.381+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_stream_dag.fetch_weather scheduled__2025-05-22T19:00:00+00:00 [queued]>
[2025-05-22T20:48:24.382+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-22T20:48:24.400+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_weather> on 2025-05-22 19:00:00+00:00
[2025-05-22T20:48:24.405+0000] {standard_task_runner.py:60} INFO - Started process 178 to run task
[2025-05-22T20:48:24.408+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_stream_dag', 'fetch_weather', 'scheduled__2025-05-22T19:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/weather_stream_dag.py', '--cfg-path', '/tmp/tmpj5ksmtnh']
[2025-05-22T20:48:24.410+0000] {standard_task_runner.py:88} INFO - Job 47: Subtask fetch_weather
[2025-05-22T20:48:24.426+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-22T20:48:24.465+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_stream_dag.fetch_weather scheduled__2025-05-22T19:00:00+00:00 [running]> on host e2f91649b69f
[2025-05-22T20:48:24.580+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_stream_dag' AIRFLOW_CTX_TASK_ID='fetch_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T19:00:00+00:00'
[2025-05-22T20:48:24.728+0000] {logging_mixin.py:188} INFO - [✓] Données météo sauvegardées : data/raw/weather/weather_2025-05-22T20-48-24.json
[2025-05-22T20:48:24.729+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-22T20:48:24.739+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_stream_dag, task_id=fetch_weather, execution_date=20250522T190000, start_date=20250522T204824, end_date=20250522T204824
[2025-05-22T20:48:24.782+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-22T20:48:24.797+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
