[2025-05-22T16:00:01.108+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_stream_dag.fetch_weather scheduled__2025-05-22T15:00:00+00:00 [queued]>
[2025-05-22T16:00:01.115+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_stream_dag.fetch_weather scheduled__2025-05-22T15:00:00+00:00 [queued]>
[2025-05-22T16:00:01.116+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-22T16:00:01.127+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_weather> on 2025-05-22 15:00:00+00:00
[2025-05-22T16:00:01.131+0000] {standard_task_runner.py:60} INFO - Started process 699 to run task
[2025-05-22T16:00:01.135+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_stream_dag', 'fetch_weather', 'scheduled__2025-05-22T15:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/weather_stream_dag.py', '--cfg-path', '/tmp/tmp9g8n7xe7']
[2025-05-22T16:00:01.139+0000] {standard_task_runner.py:88} INFO - Job 43: Subtask fetch_weather
[2025-05-22T16:00:01.154+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-22T16:00:01.188+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_stream_dag.fetch_weather scheduled__2025-05-22T15:00:00+00:00 [running]> on host 947d750798fd
[2025-05-22T16:00:01.264+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_stream_dag' AIRFLOW_CTX_TASK_ID='fetch_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T15:00:00+00:00'
[2025-05-22T16:00:01.396+0000] {logging_mixin.py:188} INFO - [✓] Données météo sauvegardées : data/raw/weather/weather_2025-05-22T16-00-01.json
[2025-05-22T16:00:01.397+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-22T16:00:01.404+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_stream_dag, task_id=fetch_weather, execution_date=20250522T150000, start_date=20250522T160001, end_date=20250522T160001
[2025-05-22T16:00:01.428+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-22T16:00:01.442+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
